// <autogenerated>
//   This file was generated by T4 code generator NhibernateMappingOutput.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using Leon.Core.Services;
using Leon.Data;
using Goceen.Website.Domain;

namespace Goceen.Website.Services
{
    public interface ISysUserService : IGenericService<SysUser>
	{

        SysUser Get(string account);

        SysUser Get(string account, string password);

        bool IsExist(string account);

        void Delete(IList<int> idList);

        void Update(SysUser entity, string password);
         
        IList<SysUser> LoadAllByPage(out long total, int page, int rows, string order, string sort);

	}
}
