// <autogenerated>
//   This file was generated by T4 code generator NhibernateMappingOutput.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using Leon.Core.Services;
using Leon.Data;
using Goceen.Website.Domain;

namespace Goceen.Website.Services
{
    public interface ISysChannelService : IGenericService<SysChannel>
	{      

        void Delete(IList<int> idList);
         
        IList<SysChannel> LoadAllByPage(out long total, int page, int rows, string order, string sort);

        bool IsExist(string name);

        IList<SysChannel> LoadAllEnable();

	}
}
